BookieTamer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('analysis.urls')),
    path('', include('datafetch.urls')),
    path('', include('bet.urls')),
    path('', include('users.urls')),
    
    # in order to go to home if blank address
    path('', RedirectView.as_view(url='home')),

]

analysis/urls.py
from django.urls import path

from . import views


app_name = 'analysis'

urlpatterns = [
    path('data/', views.MatchList.as_view(), name="data"),
    path('ajax-load-teams-by-division/', views.ajax_load_teams_by_division, name="ajax-load-teams-by-division"),

]

bet/urls.py
from django.urls import path

from . import views


app_name = 'bet'

urlpatterns = []

analysis/models.py
from django.db import models

# Create your models here.

bet/models.py
from django.db import models

from core import choices as choices_core
from core.models import BaseMatch, Team, Division


class Bet(BaseMatch):
    budget = models.IntegerField(default=0, null=True)
    home_team = models.ForeignKey('core.Team', null=True, related_name='bet_home_team', on_delete=models.SET_NULL)
    away_team = models.ForeignKey('core.Team', null=True, related_name='bet_away_team', on_delete=models.SET_NULL)
    division = models.ForeignKey('core.Division', related_name='bet_division', null=True, on_delete=models.SET_NULL)
    betted_outcome = models.CharField(max_length=1, choices=choices_core.RESULT, blank=True)
    stake = models.IntegerField(default=0, null=True)
    result = models.CharField(max_length=1, choices=choices_core.RESULT, blank=True)
    success = models.BooleanField()

core/models.py
from django.db import models

import core.choices as choices_core


""" base model for all models in the application """
class BaseModel(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseMatch(BaseModel):
    date = models.DateField(null=True)
    ft_result = models.CharField(max_length=1, choices=choices_core.RESULT, blank=False)
    odds_home = models.FloatField(null=True)
    odds_draw = models.FloatField(null=True)
    odds_away = models.FloatField(null=True)

    class Meta:
        abstract = True


class Match(BaseMatch):
    home_team = models.ForeignKey('core.Team', null=True, related_name='home_team', on_delete=models.SET_NULL)
    away_team = models.ForeignKey('core.Team', null=True, related_name='away_team', on_delete=models.SET_NULL)
    division = models.ForeignKey('core.Division', null=True, on_delete=models.SET_NULL)
    ft_home_goals = models.SmallIntegerField(null=False)
    ft_away_goals = models.SmallIntegerField(null=False)
    ht_home_goals = models.SmallIntegerField(null=False)
    ht_away_goals = models.SmallIntegerField(null=False)
    ht_result = models.CharField(max_length=1, choices=choices_core.RESULT, blank=False)

    class Meta:
        verbose_name_plural = "matches"
        ordering = ['-date']

    def __str__(self):
        return '{} - {} on {}'.format(self.home_team, self.away_team, self.date)


class Team(BaseModel):
    name = models.CharField(max_length=100, blank=True)
    division = models.ForeignKey('core.Division', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.name)


class Division(BaseModel):
    name = models.CharField(max_length=50, blank=False)
    fortuna_url = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.name)

analysis/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.shortcuts import render

from django_filters.views import FilterView

from analysis.filters import MatchFilter
from analysis.utils import divide_without_errors, color_if_higher_lower
from core import choices as choices_core
from core.models import Match, Division, Team


class MatchList(LoginRequiredMixin, FilterView):
    model = Match
    context_object_name = 'match'
    template_name = 'analysis/data.html'
    filterset_class = MatchFilter
    paginate_by = 30

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # calculate statistics data
        qs = self.object_list
        num_games = len(qs)

        # full time result percentages
        home_win_count = qs.filter(ft_result=choices_core.HOME_WIN).count()
        draw_count = qs.filter(ft_result=choices_core.DRAW).count()
        away_win_count = qs.filter(ft_result=choices_core.AWAY_WIN).count()

        home_win_percentage = divide_without_errors(home_win_count, num_games)
        draw_percentage = divide_without_errors(draw_count, num_games)
        away_win_percentage = divide_without_errors(away_win_count, num_games)

        context['home_win_percentage'] = home_win_percentage
        context['draw_percentage'] = draw_percentage
        context['away_win_percentage'] = away_win_percentage

        # avg. goals
        avg_ft_home_goals = qs.all().aggregate(Avg('ft_home_goals'))['ft_home_goals__avg']
        avg_ft_away_goals = qs.all().aggregate(Avg('ft_away_goals'))['ft_away_goals__avg']

        context['avg_ft_home_goals'] = avg_ft_home_goals
        context['avg_ft_away_goals'] = avg_ft_away_goals

        # avg. odds
        avg_home_odds = qs.all().aggregate(Avg('odds_home'))['odds_home__avg']
        avg_draw_odds = qs.all().aggregate(Avg('odds_draw'))['odds_draw__avg']
        avg_away_odds = qs.all().aggregate(Avg('odds_away'))['odds_away__avg']

        context['avg_home_odds'] = avg_home_odds
        context['avg_draw_odds'] = avg_draw_odds
        context['avg_away_odds'] = avg_away_odds

        bookie_probability_home =  divide_without_errors(1, avg_home_odds)
        bookie_probability_draw = divide_without_errors(1, avg_draw_odds)
        bookie_probability_away = divide_without_errors(1, avg_away_odds)

        context['bookie_probability_home'] = bookie_probability_home
        context['bookie_probability_draw'] = bookie_probability_draw
        context['bookie_probability_away'] = bookie_probability_away

        # color code for values
        home_win_color = color_if_higher_lower(home_win_percentage, bookie_probability_home)
        draw_color = color_if_higher_lower(draw_percentage, bookie_probability_draw)
        away_win_color = color_if_higher_lower(away_win_percentage, bookie_probability_away)

        context['home_win_color'] = home_win_color
        context['draw_color'] = draw_color
        context['away_win_color'] = away_win_color

        return context


def ajax_load_teams_by_division(request):
    division_id = request.GET.get('division_id')
    try:
        division = Division.objects.get(id=division_id)
        teams_qs = Team.objects.filter(division=division)
    except (Division.DoesNotExist, ValueError):
        division = Division.objects.all()
        teams_qs = Team.objects.filter(division__in=division)

    return render(request, 'analysis/team_choice.html', {'teams': teams_qs})

datafetch/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView

from datafetch.forms import DataFetchSettingsForm
from datafetch.models import DataFetchSettings
from datafetch.utils import get_fortuna_games

from users.models import CustomUser


@login_required
def games_to_bet_list(request):
    try:
        user_settings = DataFetchSettings.objects.filter(user=request.user)
        df = get_fortuna_games(user_settings)
        html_table = df.sort_values(by=['date', 'bet_X', 'bet_2', 'bet_1']).to_html(index=False)

        context = {
            'html_table': html_table,
        }
    except DataFetchSettings.DoesNotExist:
        no_settings = True
        context = {
            'no_settings': no_settings,
        }
    return render(request, 'datafetch/games_to_bet.html', context)


class DataFetchSettingsList(ListView):
    model = DataFetchSettings
    template_name = 'datafetch/datafetch_list.html'
    context_object_name = 'settings'

    def dispatch(self, request, *args, **kwargs):
        try:
            settings = DataFetchSettings.objects.filter(user=self.request.user)
            return super(DataFetchSettingsList, self).dispatch(request, *args, **kwargs)
        except DataFetchSettings.DoesNotExist:
            return redirect('datafetch:datafetch_settings_create')

    def get_context_data(self, **kwargs):
        context = super(DataFetchSettingsList, self).get_context_data(**kwargs)
        try:
            user = CustomUser.objects.get(id=self.request.user.id)
        except CustomUser.DoesNotExist:
            user = None

        context['settings'] = user.user_settings
        context.update({
            'title': 'Settings'
        })

        return context


class DataFetchSettingsCreate(LoginRequiredMixin, CreateView):
    model = DataFetchSettings
    template_name = 'core/base_add_update.html'
    form_class = DataFetchSettingsForm
    success_url = reverse_lazy('datafetch:datafetch_settings_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DataFetchSettingsCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(DataFetchSettingsCreate, self).get_context_data(**kwargs)
        context.update({'title': 'Settings'})
        return context


class DataFetchSettingsUpdate(LoginRequiredMixin, UpdateView):
    model = DataFetchSettings
    template_name = 'core/base_add_update.html'
    form_class = DataFetchSettingsForm

    def get_context_data(self, **kwargs):
        context = super(DataFetchSettingsUpdate, self).get_context_data(**kwargs)
        context.update({'title': 'Settings'})
        return context


def datafetch_settings_delete(request, pk):
    try:
        settings = DataFetchSettings.objects.get(id=pk)
    except DataFetchSettings.DoesNotExist:
        message = 'No Setting found'

        messages.add_message(request, messages.WARNING, message)
        return redirect('datafetch:datafetch_settings_list')

    settings.delete()
    message = 'Settings \'{}\' successfully deleted'.format(settings.name)

    messages.add_message(request, messages.SUCCESS, message)
    return redirect('datafetch:datafetch_settings_list')

analysis/templates/analysis/pages/data.html
{% extends 'analysis/base.html' %}
{% load analysis_extras %}

{% block title %}Data{% endblock %}

{% block body %}
    <div class="col-sm-12 py-4" xmlns="http://www.w3.org/1999/html">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1 class="h4 mt-1 font-weight-bold">Games
                            <span class="badge badge-pill badge-primary" data-toggle="tooltip" data-placement="right" title="Number of games displayed">{{ match.count }}</span>
{#                            <span>Home win % {{ division_list }}</span>#}
{#                            <span>Draw % {{ home_team }}</span>#}
{#                            <span>Away win % {{ away_team }}</span>#}
{#                            <span>base_filter_count % {{ base_filter_count }}</span>#}

                        </h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a href="#collapseFilters" class="btn btn-outline-primary" data-toggle="collapse" aria-controls="collapseFilters">
                            Filters
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 mx-2 collapse" id="collapseFilters">
                        <div class="row">
                            <div class="card-body">
                                <form method="get" action="">
                                    <div class="row">
                                        <div class="col-sm-3" style="border-right: 1px solid rgba(0,0,0,0.15);">
                                            <p class="filter-title">Division</p>
                                            <div class="form-group">
                                                {{ filter.form.division }}
                                            </div>
                                            <span class="show_on_division" style="display: none">
                                                <p class="filter-title">Home Team</p>
                                                    <div class="form-group">
                                                        {{ filter.form.home_team }}
                                                    </div>
                                            </span>
                                            <span class="show_on_division" style="display: none">
                                                <p class="filter-title">Away Team</p>
                                                    <div class="form-group">
                                                        {{ filter.form.away_team }}
                                                    </div>
                                            </span>
                                        </div>
                                        <div class="col-sm-3" style="border-right: 1px solid rgba(0,0,0,0.15);">
                                            <p class="filter-title">FT result</p>
                                            <div class="form-group">
                                                {{ filter.form.ft_result }}
                                            </div>
                                            <p class="filter-title">HT result</p>
                                            <div class="form-group">
                                                {{ filter.form.ht_result }}
                                            </div>
                                        </div>
                                        <div class="col-sm-3" style="border-right: 1px solid rgba(0,0,0,0.15);">
                                            <p class="filter-title">Date from</p>
                                            <div class="form-group">
                                                {{ filter.form.start_date }}
                                            </div>
                                            <p class="filter-title">Date to</p>
                                            <div class="form-group">
                                                {{ filter.form.end_date }}
                                            </div>
                                            <p class="filter-title">Home goals range</p>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                         {{ filter.form.ft_home_goals_from|css_class:"form-control" }}
                                                    </div>
                                                    <div class="col-sm-6">
                                                         {{ filter.form.ft_home_goals_to|css_class:"form-control" }}
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="filter-title">Away goals range</p>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                         {{ filter.form.ft_away_goals_from|css_class:"form-control" }}
                                                    </div>
                                                    <div class="col-sm-6">
                                                         {{ filter.form.ft_away_goals_to|css_class:"form-control" }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-3" style="border-right: 1px solid rgba(0,0,0,0.15);">
                                            <p class="filter-title">Odds home range</p>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                         {{ filter.form.odds_home_from|css_class:"form-control" }}
                                                    </div>
                                                    <div class="col-sm-6">
                                                         {{ filter.form.odds_home_to|css_class:"form-control" }}
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="filter-title">Odds draw range</p>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                         {{ filter.form.odds_draw_from|css_class:"form-control" }}
                                                    </div>
                                                    <div class="col-sm-6">
                                                         {{ filter.form.odds_draw_to|css_class:"form-control" }}
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="filter-title">Odds away range</p>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                         {{ filter.form.odds_away_from|css_class:"form-control" }}
                                                    </div>
                                                    <div class="col-sm-6">
                                                         {{ filter.form.odds_away_to|css_class:"form-control" }}
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="filter-title">Order by</p>
                                            <div class="form-group">
                                                {{ filter.form.order_by|css_class:"form-control" }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-striped">
                        <thead>
                        <tr class="text-center">
                            <th>Division</th>
                            <th>Date</th>
                            <th>Home Team</th>
                            <th>Away Team</th>
                            <th>Full time result</th>
                            <th>HG</th>
                            <th>AG</th>
                            <th>Half Time result</th>
                            <th>Half Time HG</th>
                            <th>Half Time AG</th>
                            <th>Odds Home</th>
                            <th>Odds Draw</th>
                            <th>Odds Away</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for game in filter.qs %}
                            <tr class="text-center">
                                <td class="thin">
                                    {{ game.division }}
                                </td>
                                <td class="thin">
                                    {{ game.date }}
                                </td>
                                <td class="thin">
                                    {{ game.home_team }}
                                </td>
                                <td class="thin">
                                    {{ game.away_team }}
                                </td>
                                <td class="thin">
                                    {{ game.get_ft_result_display }}
                                </td>
                                <td class="thin">
                                    {{ game.ft_home_goals }}
                                </td>
                                <td class="thin">
                                    {{ game.ft_away_goals }}
                                </td>
                                <td class="thin">
                                    {{ game.get_ht_result_display }}
                                </td>
                                <td class="thin">
                                    {{ game.ht_home_goals }}
                                </td>
                                <td class="thin">
                                    {{ game.ht_away_goals }}
                                </td>
                                <td class="thin">
                                    {{ game.odds_home }}
                                </td>
                                <td class="thin">
                                    {{ game.odds_draw }}
                                </td>
                                <td class="thin">
                                    {{ game.odds_away }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function(){
            if (window.location.href.indexOf('division') >-1) {
                $('#collapseFilters').addClass('show');
            }
        });


        $("#id_division").on('change', function(){
            var division = $('#id_division').val();
            console.log(division);
            $('#id_home_team').html("");
            if (division) {
                $(".show_on_division").show();
            }
            else {
                $(".show_on_division").hide();
            }

            $.ajax({
                url: '{% url 'ajax_get_teams_by_division' %}',
                data: {
                    'division': division
                },
                dataType: 'json',
                success: function (data) {
                    for (var i=0; i < data.teams.length; i++) {
                        var team = data.teams[i];
                        var option = new Option(team, team.id);
                        $('#id_home_team').append($(option));
                    }
                }
            });
        });




    </script>

{% endblock %}

analysis/templates/analysis/pages/home.html
{% extends 'analysis/base.html' %}

{% block title %}
    Home
{% endblock title %}




    