BookieTamer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('analysis.urls')),
    path('', include('datafetch.urls')),
    path('', include('bet.urls')),
    path('', include('users.urls')),
    
    # in order to go to home if blank address
    path('', RedirectView.as_view(url='home')),

]

analysis/urls.py
from django.urls import path

from . import views


app_name = 'analysis'

urlpatterns = [
    path('data/', views.MatchList.as_view(), name="data"),
    path('ajax-load-teams-by-division/', views.ajax_load_teams_by_division, name="ajax-load-teams-by-division"),

]

bet/urls.py
from django.urls import path

from . import views


app_name = 'bet'

urlpatterns = []

core/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path('home/', views.home, name="home"),

    path('accounts/', include('django.contrib.auth.urls')),
]

datafetch/urls.py
from django.urls import path

from . import views


app_name = 'datafetch'

urlpatterns = [
    path('games-to-bet/', views.games_to_bet_list, name="games_to_bet"),
    path('settings/create/', views.DataFetchSettingsCreate.as_view(), name="datafetch_settings_create"),
    path('settings/all/', views.DataFetchSettingsList.as_view(), name="datafetch_settings_list"),
    path('settings/<int:pk>', views.DataFetchSettingsUpdate.as_view(), name="datafetch_settings_update"),
    path('settings/<int:pk>/delete/', views.datafetch_settings_delete, name="datafetch_settings_delete"),
]

core/models.py
from django.db import models

import core.choices as choices_core


""" base model for all models in the application """
class BaseModel(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseMatch(BaseModel):
    date = models.DateField(null=True)
    ft_result = models.CharField(max_length=1, choices=choices_core.RESULT, blank=False)
    odds_home = models.FloatField(null=True)
    odds_draw = models.FloatField(null=True)
    odds_away = models.FloatField(null=True)

    class Meta:
        abstract = True


class Match(BaseMatch):
    home_team = models.ForeignKey('core.Team', null=True, related_name='home_team', on_delete=models.SET_NULL)
    away_team = models.ForeignKey('core.Team', null=True, related_name='away_team', on_delete=models.SET_NULL)
    division = models.ForeignKey('core.Division', null=True, on_delete=models.SET_NULL)
    ft_home_goals = models.SmallIntegerField(null=False)
    ft_away_goals = models.SmallIntegerField(null=False)
    ht_home_goals = models.SmallIntegerField(null=False)
    ht_away_goals = models.SmallIntegerField(null=False)
    ht_result = models.CharField(max_length=1, choices=choices_core.RESULT, blank=False)

    class Meta:
        verbose_name_plural = "matches"
        ordering = ['-date']

    def __str__(self):
        return '{} - {} on {}'.format(self.home_team, self.away_team, self.date)


class Team(BaseModel):
    name = models.CharField(max_length=100, blank=True)
    division = models.ForeignKey('core.Division', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.name)


class Division(BaseModel):
    name = models.CharField(max_length=50, blank=False)
    fortuna_url = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.name)

core/forms.py
from django import forms


""" default form styling using Boostrap classes """
class BootstrapStylingBaseForm(forms.Form):
    field_cols = None

    def __init__(self, *args, **kwargs):
        super(BootstrapStylingBaseForm, self).__init__(*args, **kwargs)
        field_index = 0

        while field_index <= len(self.fields):
            for field in self.fields:
                # used to define col-lg-xx Bootstrap class for each field
                if self.field_cols:
                    if field in self.field_cols:
                        self.fields[field].widget.attrs.update({'count_cols': self.field_cols.get(field)})
                else:
                    self.fields[field].widget.attrs.update({'count_cols': 12})
            field_index += 1

core/views.py
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


def home(request):

    context = {
    }
    return render(request, 'core/pages/home.html', context)

core/templates/core/snippets/base_registration_form.html
{% load crispy_forms_tags %}

<div class="container text-dark">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h2>{{ title }}</h2>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-success" type="submit">{{ button }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
  

core/templates/core/snippets/header_navbar.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-light static-top">
    <ul class="navbar-nav mr-4">
        <li class="nav-item"><a href="{% url "home" %}"><img src="{% static "core/logo.png" %}" width="70" height="50"></a></li>
    </ul>
    <ul class="navbar-nav text-dark">
        <li class="nav-item mx-2"><a class="nav-link" href="{% url 'home' %}"><i class="fas fa-tachometer-alt"></i> Dashboard</a></li>
        {% if user.is_authenticated %}
            <li class="nav-item mx-2"><a class="nav-link" href="{% url "analysis:data" %}"><i class="fas fa-database"></i> Data</a></li>
            <li class="nav-item mx-2"><a class="nav-link" href="{% url "datafetch:games_to_bet" %}"><i class="fas fa-cloud-download-alt"></i> Get games</a></li>
            <li class="nav-item mx-2"><a class="nav-link" href="#"><i class="fas fa-list-ul"></i> Bet list</a></li>
            {% if user.user_settings %}
                <li class="nav-item mx-2"><a class="nav-link" href="{% url "datafetch:datafetch_settings_list" %}"><i class="fas fa-wrench"></i> Setting</a></li>
            {% else %}
                <li class="nav-item mx-2"><a class="nav-link" href="{% url "datafetch:datafetch_settings_create" %}"><i class="fas fa-wrench"></i> Settings
                    <i class="fas fa-exclamation-circle text-danger" data-toggle="tooltip" title="You have no settings, click and create one first." data-placement="right"></i>
                </a></li>
            {% endif %}
        {% endif %}
    </ul>
    <ul class="navbar-nav text-dark ml-auto">
        {% if not user.is_authenticated %}
            <li class="nav-item mx-2"><a class="nav-link" href="{% url 'signup' %}"><i class="fas fa-user-plus"></i> Sign up</a></li>
            <li class="nav-item mx-2"><a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Login</a></li>
        {% else %}
            
            <!-- username with dropdown -->
            <div class="dropdown show">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i> {{ user.username }}</a>
            
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                </div>
            </div>

            <li class="nav-item mx-2"><a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-in-alt"></i> Logout</a></li>
        {% endif %}
    </ul>
</nav>

core/templates/core/snippets/messages_and_form_errors.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

core/templates/core/snippets/pagination.html
{% if is_paginated %}
    <div class="col-lg-12 mt-3 d-flex">
        {% if page_obj.has_other_pages %}
            <ul class="pagination mx-auto">

                <!-- Previous page -->
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page=1">&laquo;</a></li>
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&lsaquo;</a></li>
                {% else %}
                    <li class="disabled"></li>
                {% endif %}

                <!-- Pagination -->
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                    {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                        <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                <!-- Next page -->
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">&rsaquo;</a></li>
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ paginator.num_pages }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endif %}