BookieTamer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('analysis.urls')),
    path('', include('datafetch.urls')),
    path('', include('bet.urls')),
    path('', include('users.urls')),
    
    # in order to go to home if blank address
    path('', RedirectView.as_view(url='home')),

]

bet/urls.py
from django.urls import path

from . import views


app_name = 'bet'

urlpatterns = []

datafetch/urls.py
from django.urls import path

from . import views


app_name = 'datafetch'

urlpatterns = [
    path('games-to-bet/', views.games_to_bet_list, name="games_to_bet"),
    path('settings/create/', views.DataFetchSettingsCreate.as_view(), name="datafetch_settings_create"),
    path('settings/all/', views.DataFetchSettingsList.as_view(), name="datafetch_settings_list"),
    path('settings/<int:pk>', views.DataFetchSettingsUpdate.as_view(), name="datafetch_settings_update"),
    path('settings/<int:pk>/delete/', views.datafetch_settings_delete, name="datafetch_settings_delete"),
]

datafetch/models.py
from django.db import models
from django.shortcuts import reverse

from core.models import BaseModel


class DataFetchSettings(BaseModel):
    name = models.CharField(max_length=256, blank=True)
    max_difference_x_probability = models.FloatField(null=True, blank=True)
    odds_1_min_probability = models.FloatField(null=True, blank=True)
    odds_1_max_probability = models.FloatField(null=True, blank=True)
    odds_2_min_probability = models.FloatField(null=True, blank=True)
    odds_2_max_probability = models.FloatField(null=True, blank=True)
    date_offset = models.IntegerField(default=7, null=False)

    user = models.ForeignKey('users.CustomUser', related_name='user_settings', on_delete=models.CASCADE)
    leagues = models.ManyToManyField('core.Division', related_name='leagues', blank=True)

    def get_absolute_url(self):
        return reverse('datafetch:datafetch_settings_update', kwargs={'pk': self.pk })

datafetch/forms.py
from django import forms

from .models import DataFetchSettings
from core.forms import BootstrapStylingBaseForm


class DataFetchSettingsForm(BootstrapStylingBaseForm, forms.ModelForm):
    field_cols = {
        'date_offset': 2,
        'leagues': 4,
        'odds_1_min_probability': 2,
        'odds_1_max_probability': 2,
        'odds_2_min_probability': 2,
        'odds_2_max_probability': 2,
        'max_difference_x_probability': 2,
        'name': 12,
    }


    fieldsets = (
        {
            'title': 'Time frame and Leagues',
            'icon': '',
            'icon_color': '',
            'fields': ('date_offset', 'leagues')
        },
        {
            'title': 'Odds settings',
            'icon': '',
            'icon_color': '',
            'fields': ('odds_1_min_probability',
                       'odds_1_max_probability',
                       'odds_2_min_probability',
                       'odds_2_max_probability',
                       'max_difference_x_probability',
                       )
         },
        {
            'title': 'Name',
            'icon': '',
            'fields': ('name')
        }
    )

    class Meta:
        model = DataFetchSettings
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(DataFetchSettingsForm, self).__init__(*args, **kwargs)
        self.fields['leagues'].widget.attrs.update({'class': 'js-multiple-select2', 'style': 'width: 100%'})

datafetch/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView

from datafetch.forms import DataFetchSettingsForm
from datafetch.models import DataFetchSettings
from datafetch.utils import get_fortuna_games

from users.models import CustomUser


@login_required
def games_to_bet_list(request):
    try:
        user_settings = DataFetchSettings.objects.filter(user=request.user)
        df = get_fortuna_games(user_settings)
        html_table = df.sort_values(by=['date', 'bet_X', 'bet_2', 'bet_1']).to_html(index=False)

        context = {
            'html_table': html_table,
        }
    except DataFetchSettings.DoesNotExist:
        no_settings = True
        context = {
            'no_settings': no_settings,
        }
    return render(request, 'datafetch/games_to_bet.html', context)


class DataFetchSettingsList(ListView):
    model = DataFetchSettings
    template_name = 'datafetch/datafetch_list.html'
    context_object_name = 'settings'

    def dispatch(self, request, *args, **kwargs):
        try:
            settings = DataFetchSettings.objects.filter(user=self.request.user)
            return super(DataFetchSettingsList, self).dispatch(request, *args, **kwargs)
        except DataFetchSettings.DoesNotExist:
            return redirect('datafetch:datafetch_settings_create')

    def get_context_data(self, **kwargs):
        context = super(DataFetchSettingsList, self).get_context_data(**kwargs)
        try:
            user = CustomUser.objects.get(id=self.request.user.id)
        except CustomUser.DoesNotExist:
            user = None

        context['settings'] = user.user_settings
        context.update({
            'title': 'Settings'
        })

        return context


class DataFetchSettingsCreate(LoginRequiredMixin, CreateView):
    model = DataFetchSettings
    template_name = 'core/base_add_update.html'
    form_class = DataFetchSettingsForm
    success_url = reverse_lazy('datafetch:datafetch_settings_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DataFetchSettingsCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(DataFetchSettingsCreate, self).get_context_data(**kwargs)
        context.update({'title': 'Settings'})
        return context


class DataFetchSettingsUpdate(LoginRequiredMixin, UpdateView):
    model = DataFetchSettings
    template_name = 'core/base_add_update.html'
    form_class = DataFetchSettingsForm

    def get_context_data(self, **kwargs):
        context = super(DataFetchSettingsUpdate, self).get_context_data(**kwargs)
        context.update({'title': 'Settings'})
        return context


def datafetch_settings_delete(request, pk):
    try:
        settings = DataFetchSettings.objects.get(id=pk)
    except DataFetchSettings.DoesNotExist:
        message = 'No Setting found'

        messages.add_message(request, messages.WARNING, message)
        return redirect('datafetch:datafetch_settings_list')

    settings.delete()
    message = 'Settings \'{}\' successfully deleted'.format(settings.name)

    messages.add_message(request, messages.SUCCESS, message)
    return redirect('datafetch:datafetch_settings_list')

datafetch/templates/datafetch/datafetch_list.html
{% extends 'core/base.html' %}
{% load core_extras %}

{% block title %}
    Games to bet
{% endblock title %}

{% block body %}

     <div class="col-sm-12 py-4">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1 class="h4 mt-1 font-weight-bold">Your settings</h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a href="{% url 'datafetch:datafetch_settings_create' %}">
                            <button class="btn btn-outline-primary show-all">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                Add settings
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">

                    {% include 'core/snippets/messages_and_form_errors.html' %}

                    <table class="table table-striped">
                        <thead>
                        <tr class="text-center">
                            <th>Name</th>
                            <th>Leagues</th>
                            <th>X max prob difference</th>
                            <th>1 min prob</th>
                            <th>1 max prob </th>
                            <th>2 min prob</th>
                            <th>2 max prob</th>
                            <th>Days offset</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for setting in settings.all %}
                            <tr class="text-center">
                                <td class="thin">
                                    {{ setting.name }}
                                </td>
                                <td class="thin">
                                    {% for league in setting.leagues.all %}
                                    {{ league }}</br>
                                    {% endfor %}
                                </td>
                                <td class="thin">
                                    {{ setting.max_difference_x_probability }}
                                </td>
                                <td class="thin">
                                    {{ setting.odds_1_min_probability }}
                                </td>
                                <td class="thin">
                                    {{ setting.odds_1_max_probability }}
                                </td>
                                <td class="thin">
                                    {{ setting.odds_2_min_probability }}
                                </td>
                                <td class="thin">
                                    {{ setting.odds_2_max_probability }}
                                </td>
                                <td class="thin">
                                    {{ setting.date_offset }}
                                </td>
                                <td class="thin">
                                    <a href="{% url 'datafetch:datafetch_settings_update' setting.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>
                                    <a href="{% url 'datafetch:datafetch_settings_delete' setting.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
     </div>

    <script>

    </script>
{% endblock %}

datafetch/templates/datafetch/games_to_bet.html
{% extends 'core/base.html' %}
{% load core_extras %}

{% block title %}
    Games to bet
{% endblock title %}

{% block body %}

     <div class="col-sm-12 py-4">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-6">
                        {% if no_settings %}
                            <h1 class="h4 mt-1 font-weight-bold">Go to settings and select criteria for the games</h1>
                        {% else %}
                            <h1 class="h4 mt-1 font-weight-bold">Games to bet on</h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <button class="btn btn-outline-primary js-show-to-bet">Show to bet</button>
                        <button class="btn btn-outline-primary js-show-all">Show all</button>
                    </div>
                     {% endif %}
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        {{ html_table|safe }}
                    </div>
                </div>
            </div>
        </div>
     </div>

    <script>
        $(document).ready(function(){
            $('.dataframe').addClass('table table-striped table-dark');
            $(this).find('thead').find('tr').addClass('text-left');

            $('thead tr:first').addClass('to_bet');
            $('tbody td:contains(True)').parent().addClass('text-success').addClass('to_bet');

            var removeColumnName = "<th class='text-center'>Hide</i></th>";
            $('thead').find('tr').append(removeColumnName);

            var removeButton = "<td class='text-center text-success'><i class=\"fas fa-check mark-hide\" style='cursor: pointer;'></i></td>";
            $('tbody').children('tr').append(removeButton);
            $('.mark-hide').on('click', function () {
                $(this).parents('tr').fadeOut();
            });

            $('.js-show-all').on('click', function () {
                $('tbody').children().fadeIn();
            });

            $('.js-show-to-bet').on('click', function () {
                $('tr:not(".to_bet")').fadeOut();
            });

        });
    </script>
{% endblock %}